### ISSUE TITLE
ValueError: format not resolved, probably missing URL scheme or undefined destination target for 'upgrade-scripts-for-a-language'

### ISSUE THREAD

**Issue by CaledoniaProject** [rst2pdf/rst2pdf#1063]
I'm trying to convert the document here to a PDF file: https://github.com/github/codeql/tree/main/docs/codeql

I first cloned the master branch and appended to the `conf.py`:

```
extensions = ['rst2pdf.pdfbuilder']
pdf_stylesheets = ['twocolumn']
pdf_documents = [('contents', u'rst2pdf', u'Sample rst2pdf doc', u'Your Name'),]
```

Then I invoke `sphinx-build -b pdf $PWD build` to build the PDF but it fails

```
[WARNING] flowables.py:936 BoundByWidth too wide to fit in frame (702.0 > 513.3826771653543): <BoundByWidth at 0x1156a7c40> containing: ['<XXPreformatted at 0x1156a7df0>']
[WARNING] flowables.py:936 BoundByWidth too wide to fit in frame (702.0 > 513.3826771653543): <BoundByWidth at 0x115a8a760> containing: ['<XXPreformatted at 0x115a8a1c0>']
[ERROR] pdfbuilder.py:161 Failed to build doc
Traceback (most recent call last):
  File "/usr/local/homebrew/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 158, in write
    docwriter.write(doctree, destination)
  File "/usr/local/homebrew/lib/python3.9/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/local/homebrew/lib/python3.9/site-packages/rst2pdf/pdfbuilder.py", line 697, in translate
    createpdf.RstToPdf(
  File "/usr/local/homebrew/lib/python3.9/site-packages/rst2pdf/createpdf.py", line 689, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/platypus/doctemplate.py", line 1176, in multiBuild
    self.canv.save()
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfgen/canvas.py", line 1277, in save
    self._doc.SaveToFile(self._filename, self)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 221, in SaveToFile
    data = self.GetPDFData(canvas)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 247, in GetPDFData
    return self.format()
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 429, in format
    IOf = IO.format(self)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 882, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 76, in format
    f = element.format(document)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 1619, in format
    return D.format(document)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 689, in format
    L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 689, in <listcomp>
    L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 76, in format
    f = element.format(document)
  File "/usr/local/homebrew/lib/python3.9/site-packages/reportlab/pdfbase/pdfdoc.py", line 1783, in format
    if f is None: raise ValueError("format not resolved, probably missing URL scheme or undefined destination target for '%s'" % self.name)
ValueError: format not resolved, probably missing URL scheme or undefined destination target for 'upgrade-scripts-for-a-language'
FAILED
build succeeded.
```

Environment

1. homebrew Python 3.9 on Mac
2. rst2pdf 0.99

**Comment by akrabat** [comment]
The `about-ql-packs.rst` file contains:

    (see `Upgrade scripts for a language <#upgrade-scripts-for-a-language>`__ below.)
    
It seems that reportlab can't work out where to link `#upgrade-scripts-for-a-language`.

**Comment by CaledoniaProject** [comment]
Can you update the code to ignore such error and print a warning instead?

**Comment by lornajane** [comment]
I'm actually not sure that the link syntax used here is valid, so that's the first question. Also I think the suggestion to warn rather than error is a good one; we'd be happy to have a patch (and test!) for this use case.
