### ISSUE TITLE
pdf_appendices split bug

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#393]
```
Using the latest hg Sphinx with r2417 of rst2pdf.

Attempting to build the doc tree for libLAS at http://hg.liblas.org/main ./docs

'make pdf'

ght community [ERROR] pdfbuilder.py:129 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
  File "/Library/Python/2.6/site-packages/rst2pdf-0.17.dev_r2417-py2.6.egg/rst2pdf/pdfbuilder.py", line 121, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File "/Library/Python/2.6/site-packages/rst2pdf-0.17.dev_r2417-py2.6.egg/rst2pdf/pdfbuilder.py", line 218, in assemble_doctree
    index_nodes=genindex_nodes(genindex)
  File "/Library/Python/2.6/site-packages/rst2pdf-0.17.dev_r2417-py2.6.egg/rst2pdf/pdfbuilder.py", line 396, in genindex_nodes
    output.append('`%s <#%s>`_'%(entryname,nodes.make_id(links[0])))
  File "/Library/Python/2.6/site-packages/docutils-0.6-py2.6.egg/docutils/nodes.py", line 1838, in make_id
    id = string.lower()
AttributeError: 'tuple' object has no attribute 'lower'

```

Original issue reported on code.google.com by `hobu....@gmail.com` on 17 Feb 2011 at 4:41

**Comment by lornajane** [comment]
Attempting to replicate this today (reportlab 3.5.6) produces the same error as seen in #678 - so this issue is blocked for now

**Comment by lornajane** [comment]
Looks like the related bug #678 was already fixed and the liblas project doesn't render PDFs any more anyway. So I'll close this but if you're seeing the same bug, please open a new issue with a replication case we can use to test. Thanks!
