### ISSUE TITLE
rst2pdf.0.16 sphinx.1.1, index directive => AttributeError: 'tuple' object has no attribute 'lower'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#426]
```
What steps will reproduce the problem?
1. add a **.. index::** directive in a rst source file
2. try to build the pdf with sphinx

What is the expected output? What do you see instead?
I expected the creation of a pdf file,
I got an exception, see full traceback at end of issue description

I identified the origin of the problem (changeset 3124, Georg Brandl),
+ before the change, **links** is a list of strings: [ target, .. ]
+ after the change,  **links** is a list of tuples:  [ (main, target), ...]
and made a correction that worked,
(or more exactly allowed me to step to the next problem)

In the pdf that was created, most index entries were linked to a wrong target
(file_ABC#index-0, file_XYZ#index-0, ...) are all linked to a single target
that is most logical as the **index-N** ids are relative to the source document
(N is a 0 based serial-number specific to each document)
and cannot be used in the context of concatenated treee

I made it work by replacing **index-N** ids by **docname-index-N** ids
in the tree just before writing the pdf file, as I did not want to modify the 
sphinx code.

See attached file that contains 3 corrections  that can surely be ameliorated,
as I am quite novice with sphinx/rst2pdf:

* docutils.get_language compatibility (already corrected in your svn trunk)
* index entry, compability with sphinx 1.1 
* index entries, replace **index-N** by **docname-index-N*



Please answer the following questions, they are *very* important:

* Version of rst2pdf?
0.16
* Version of reportlab?
2.5
* Are you using wordaxe, and if true, what version?
No
* Are you using rst2pdf with Sphinx, and if true, what version?
1.1
Please provide any additional information below.



full Traceback

            Traceback (most recent call last):
              File "C:\Python27\lib\site-packages\rst2pdf-0.16-py2.7.egg\rst2pdf\pdfbuilder.py", line 129, in write
                appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
              File "C:\Python27\lib\site-packages\rst2pdf-0.16-py2.7.egg\rst2pdf\pdfbuilder.py", line 226, in assemble_doctree
                index_nodes=genindex_nodes(genindex)
              File "C:\Python27\lib\site-packages\rst2pdf-0.16-py2.7.egg\rst2pdf\pdfbuilder.py", line 410, in genindex_nodes
                output.append('`%s <#%s>`_'%(entryname,nodes.make_id(links[0])))
              File "C:\Python27\lib\site-packages\docutils-0.8.1-py2.7.egg\docutils\nodes.py", line 1838, in make_id
                id = string.lower()
            AttributeError: 'tuple' object has no attribute 'lower'


```

Original issue reported on code.google.com by `guydalbe...@gmail.com` on 1 Dec 2011 at 4:04

Attachments:
- [pdfbuilder.py](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-426/comment-0/pdfbuilder.py)

**Comment by lornajane** [comment]
Closing due to inactivity (and I think the versions of sphinx have moved on enough that this probably no longer applies)
