### ISSUE TITLE
Tests fail under Windows

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#457]
```
What steps will reproduce the problem?
from the project dir execute
nosetests -i regulartest -i sphinxtest

What is the expected output? What do you see instead?
Expected is a passing test report
E
======================================================================
ERROR: Failure: ImportError (cannot import name SIGKILL)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\nose\loader.py", line 390, in loadTestsFromName
    addr.filename, addr.module)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 39, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "C:\Python27\lib\site-packages\nose\importer.py", line 86, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "J:\dev\workspace\pythonxy-xy-27\src\python\rst2pdf\__workspace\rst2pdf-0.92\rst2pdf\tests\__init__.py", line 2, in <module>
    from test import regulartest, releasetest, sphinxtest
  File "J:\dev\workspace\pythonxy-xy-27\src\python\rst2pdf\__workspace\rst2pdf-0.92\rst2pdf\tests\test.py", line 3, in <module>
    from autotest import MD5Info, PathInfo, globjoin
  File "J:\dev\workspace\pythonxy-xy-27\src\python\rst2pdf\__workspace\rst2pdf-0.92\rst2pdf\tests\autotest.py", line 24, in <module>
    from execmgr import textexec, default_logger as log
  File "J:\dev\workspace\pythonxy-xy-27\src\python\rst2pdf\__workspace\rst2pdf-0.92\rst2pdf\tests\execmgr.py", line 28, in <module>
    from signal import SIGTERM, SIGKILL
ImportError: cannot import name SIGKILL

----------------------------------------------------------------------
Ran 1 test in 0.453s

FAILED (errors=1)

Please answer the following questions, they are *very* important:

* Version of rst2pdf?
0.92

* Version of reportlab?
2.5

* Are you using wordaxe, and if true, what version?
N/A

* Are you using rst2pdf with Sphinx, and if true, what version?
N/A

Please provide any additional information below.
wrapper is Linux only (why?)

```

Original issue reported on code.google.com by `grizzly.nyo` on 1 Jul 2012 at 5:37

**Comment by lornajane** [comment]
We don't have any windows users in the project, if anyone can replicate the problem and help us with a patch, that would be excellent!

**Comment by fleimgruber** [comment]
I can replicate this and have a fix. I do run Python 3 only though, so will wait for support to land in master first.

**Comment by lornajane** [comment]
Master branch is Python 3 now, and we have switched to pytest for tests. Any news on how this behaves on Windows would be welcome if we have any Windows users that can grab master and try the tests.

**Comment by fleimgruber** [comment]
I tried to run the test suite on Windows but the dependency on `fitz` causes trouble. I tried with `fitz==0.0.1.dev2` from pip which fails with `ModuleNotFoundError: No module named 'frontend'` and with the current master which fails with `AttributeError: module 'fitz' has no attribute 'open'`. Could you provide `requirements-dev.txt` or similar to see the versions of development dependencies?

**Comment by lornajane** [comment]
I had something similar to this on my Linux box the other and I borrowed the setup lines from `.travis.yml` and that sorted it all out. I used these lines:

```
pip install --upgrade setuptools
pip install pytest
pip install -c requirements.txt -e .[tests,sphinx,images,svgsupport,aafiguresupport,mathsupport,rawhtmlsupport]
```

Maybe this will help you and maybe we should have this in the docs somewhere!

**Comment by fleimgruber** [comment]
Thanks, that worked. There is only one test failing, see below. It fails because it can't find the `plantuml` executable. I installed plantuml with the compiled jar file, upstream does not provide an .exe installer.

```
====================================================== FAILURES =======================================================
_________________________________________________ test_uml_extension __________________________________________________
File 'output\\test_uml_extension.pdf' was not generated:

c:\users\user\dev\rst2pdf\rst2pdf\rson.py:140: FutureWarning: Possible nested set at position 2
  splitter = re.compile(pattern).split
[INFO] createpdf.py:1580 Importing extension module 'vectorpdf'
[INFO] createpdf.py:1580 Importing extension module 'inkscape'
[INFO] createpdf.py:1580 Importing extension module 'plantuml'
[INFO] languages.py:38 Language 'en_US' not supported by Docutils, using 'en' instead.
[INFO] styles.py:81 Using stylesheets:
[INFO] styles.py:114 FontPath:['.', 'c:\\users\\user\\dev\\rst2pdf\\rst2pdf\\fonts']
[INFO] styles.py:115 StylePath:['.', 'c:\\users\\user\\dev\\rst2pdf\\rst2pdf\\styles', 'C:\\Users\\User/.rst2pdf/styles']
[INFO] languages.py:38 Language 'en_US' not supported by Docutils, using 'en' instead.
Traceback (most recent call last):
  File "c:\users\user\dev\rst2pdf\rst2pdf\extensions\plantuml.py", line 69, in gather_elements
    p = subprocess.Popen(args.split(), stdout=tfile,
  File "C:\Users\User\AppData\Local\Continuum\Miniconda3\envs\rst2pdf\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\User\AppData\Local\Continuum\Miniconda3\envs\rst2pdf\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Continuum\Miniconda3\envs\rst2pdf\Scripts\rst2pdf-script.py", line 33, in <module>
    sys.exit(load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')())
  File "c:\users\user\dev\rst2pdf\rst2pdf\createpdf.py", line 1465, in main
    RstToPdf(
  File "c:\users\user\dev\rst2pdf\rst2pdf\createpdf.py", line 554, in createPdf
    elements = self.gen_elements(self.doctree)
  File "c:\users\user\dev\rst2pdf\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\user\dev\rst2pdf\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\user\dev\rst2pdf\rst2pdf\basenodehandler.py", line 208, in gather_elements
    return client.gather_elements(node, style=style)
  File "c:\users\user\dev\rst2pdf\rst2pdf\createpdf.py", line 386, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "c:\users\user\dev\rst2pdf\rst2pdf\basenodehandler.py", line 253, in elemdispatch
    elements = self.getelements(client, node, style)
  File "c:\users\user\dev\rst2pdf\rst2pdf\basenodehandler.py", line 228, in getelements
    elements = self.gather_elements(client, node, style)
  File "c:\users\user\dev\rst2pdf\rst2pdf\extensions\plantuml.py", line 75, in gather_elements
    % self.builder.config.plantuml)
AttributeError: 'UMLHandler' object has no attribute 'builder'

=============================================== short test summary info ===============================================
FAILED rst2pdf/tests/input/test_uml_extension.txt::test_uml_extension
================================ 1 failed, 286 passed, 23 skipped in 968.06s (0:16:08) **================================**
```

**Comment by fleimgruber** [comment]
I now run with a batch file that handles the java+jar invocation and adapted the test code to call the batch file (separate issue), now I get the test output below. I don't know how to further debug as the test suite is different from my usual pytest experience (fixtures + test_* functions).

```
============================= test session starts =============================
platform win32 -- Python 3.8.3, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- C:\Users\User\AppData\Local\Continuum\miniconda3\envs\rst2pdf\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\User\dev\rst2pdf
collecting ... collected 310 items / 309 deselected / 1 selected

input\test_uml_extension.txt::test_uml_extension FAILED                  [100%]
rst2pdf\tests\input\test_uml_extension.txt:0 (test_uml_extension)
conftest.CompareException: assert (8.25 / 161.31790161132812) < 0.04
 +  where 161.31790161132812 = max(161.31790161132812, 153.06790161132812)

Assertion failed

Assertion failed

Assertion failed


================================== FAILURES ===================================
_____________________________ test_uml_extension ______________________________
conftest.CompareException: assert (8.25 / 161.31790161132812) < 0.04
 +  where 161.31790161132812 = max(161.31790161132812, 153.06790161132812)
=========================== short test summary info ===========================
FAILED input\test_uml_extension.txt::test_uml_extension
===================== 1 failed, 309 deselected in 33.08s ======================
```

**Comment by akrabat** [comment]
The tests work by generating a PDF and then comparing it to a reference PDF which is considered correct.

In this case, you should find that there's an `output/test_uml_extension.pdf` file that your installation created. There's also a `reference/test_uml_extension.pdf`. If you open them both you should see significant differences.

**Comment by fleimgruber** [comment]
Results are here: https://filebin.net/mwk827nrhv85sguz. The two files have slightly different scaling.

**Comment by lornajane** [comment]
If the only test failure is a uml scaling change, I think I'll call this good and close the issue!further information is welcome and we can reopen the issue if there is more to do
