### ISSUE TITLE
bootstrap.py fails to generate the buildout script

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#500]
```
What steps will reproduce the problem?
1. Launch bootstrap.py

What is the expected output? What do you see instead?

Expected: the "buildout" script is generated in /bin

Result:

Downloading 
http://pypi.python.org/packages/2.7/s/setuptools/setuptools-0.6c11-py2.7.egg
Traceback (most recent call last):
  File "C:\extra\rst2pdf-0.93\bootstrap.py", line 110, in <module>
    ws.require('zc.buildout' + VERSION)
  File "c:\users\obenard\appdata\local\temp\tmpqhdjdf\setuptools-0.6c11-py2.7.egg\pkg_resources.py", line 666, in require
  File "c:\users\obenard\appdata\local\temp\tmpqhdjdf\setuptools-0.6c11-py2.7.egg\pkg_resources.py", line 569, in resolve
pkg_resources.VersionConflict: (setuptools 0.6c11 
(c:\users\obenard\appdata\local\temp\tmpqhdjdf\setuptools-0.6c11-py2.7.egg), 
Requirement.parse('setuptools>=0.7'))

Please answer the following questions, they are *very* important:

* Version of rst2pdf?

0.93

* Version of reportlab?

2.7

* Are you using wordaxe, and if true, what version?

No

* Are you using rst2pdf with Sphinx, and if true, what version?

No

Please provide any additional information below.

System: Win 7
Python: 2.7.5

This problem seems to come from an outdated ez_setup.py script when installing 
setuptools. Somewhere a requirement states that setuptools version must be at 
least 0.7 but the script downloads a 0.6 version.

I tried to fix the problem and came to a simple solution: replace the url 
(http://peak.telecommunity.com/dist/ez_setup.py) by the one from a compatible 
version of setuptools (for example, the one from the 0.7.4 version -- 
https://bitbucket.org/pypa/setuptools/raw/0.7.4/ez_setup.py). This change 
allowed me to generate the buildout script and install rst2pdf properly with it.

```

Original issue reported on code.google.com by `oben...@generixgroup.com` on 10 Jul 2013 at 9:28

**Comment by lornajane** [comment]
Bootstrap.py is no longer used in this project, closing.
