### ISSUE TITLE
vectorpdf_r2p extension load fails if pdfrw module is not installed

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#510]
```
When pdfrw module is not installed, rst2pdf version 0.93 fails with this 
traceback:

Traceback (most recent call last):
  [...]
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 1461, in main
    add_extensions(options)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 1588, in add_extensions
    module.install(createpdf, options)
  File "C:\Python27\lib\site-packages\rst2pdf\extensions\vectorpdf_r2p.py", line 154, in install
    LazyImports.pdfinfo = pdfrw
NameError: global name 'pdfrw' is not defined

```

Original issue reported on code.google.com by `smishla...@gmail.com` on 6 Nov 2013 at 7:45

**Comment by lornajane** [comment]
Both pdfrw and vectorpdf will be removed soon. Closing.
