### ISSUE TITLE
Page break in definition list

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#511]
```
When a definition list overflows to a new page, following exception is raised:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "C:\Python27\lib\site-packages\reportlab\platypus\doctemplate.py", line 960, in multiBuild
    self.build(tempStory, **buildKwds)
  File "C:\Python27\lib\site-packages\reportlab\platypus\doctemplate.py", line 880, in build
    self.handle_flowable(flowables)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 770, in handle_flowable
    S = frame.split(f,canv)
  File "C:\Python27\lib\site-packages\reportlab\platypus\frames.py", line 201, in split
    r = flowable.split(self._aW, y-p-s)
  File "C:\Python27\lib\site-packages\rst2pdf\flowables.py", line 304, in split
    text[l].wrap(w-dw,h-lh-dh)
  File "C:\Python27\lib\site-packages\wordaxe\rl\NewParagraph.py", line 527, in wrap
    return self.i_wrap(availW, availH, max_widths)
  File "C:\Python27\lib\site-packages\wordaxe\rl\NewParagraph.py", line 668, in i_wrap
    assert lines
AssertionError


rst2pdf version 0.93, reportlab version 2.7, wordaxe version 1.0.1.

Attached is test input file producing this error.
```

Original issue reported on code.google.com by `smishla...@gmail.com` on 7 Nov 2013 at 11:27

Attachments:
- [test_long_definition_list.txt](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-511/comment-0/test_long_definition_list.txt)

**Comment by lornajane** [comment]
Due to the age of this issue and the missing artefacts (examples, and patch), and the fact that we don't use wordaxe any more, I'm closing this issue. If you think you are seeing it, I'd love a new issue with the rst that causes the problem so we can look at it again.
