### ISSUE TITLE
exception in rst2pdf when the sphinx.ext.todo is present and used 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#513]
```
What steps will reproduce the problem?
1. Attempt to build pdf output from Sphinx with rst2pdf while using the 
sphinx.ext.todo extension, with a todo item in the rst file, crash rst2pdf
2. e.g. .. todo:: Content, please
3. This crash can be toggled by enabling / disabling the todo extension
4. The HTML export of sphinx works fine with the todo extension

What is the expected output? What do you see instead?

I would expect the pdf to be output, with, or without, the todo item 
and todo index. 
------------------------------
writing SPHINX_PROJECT_NAME ... [ERROR] pdfbuilder.py:130 'ids'
Traceback (most recent call last):
  File "E:\tools\rst2pdf-0.93\rst2pdf\pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "c:\Python275_32\lib\site-packages\docutils-0.11-py2.7.egg\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "E:\tools\rst2pdf-0.93\rst2pdf\pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "E:\tools\rst2pdf-0.93\rst2pdf\createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "E:\tools\rst2pdf-0.93\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "E:\tools\rst2pdf-0.93\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "E:\tools\rst2pdf-0.93\rst2pdf\basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "E:\tools\rst2pdf-0.93\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "E:\tools\rst2pdf-0.93\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "E:\tools\rst2pdf-0.93\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "E:\tools\rst2pdf-0.93\rst2pdf\genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "E:\tools\rst2pdf-0.93\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "E:\tools\rst2pdf-0.93\rst2pdf\basenodehandler.py", line 245, in elemdispatch
    for i in node['ids']:
  File "c:\Python275_32\lib\site-packages\docutils-0.11-py2.7.egg\docutils\nodes.py", line 567, in __getitem__
    return self.attributes[key]
KeyError: 'ids'
FAILED
build succeeded.
Build finished. The PDF files are in build/pdf
------------------------------

Incomplete or invalid PDF is output (it does not open in Acrobat reader)

Please answer the following questions, they are *very* important:

* Version of rst2pdf?

0.93

* Version of reportlab?

 reportlab 3.0

* Are you using wordaxe, and if true, what version?

* Are you using rst2pdf with Sphinx, and if true, what version?

Yes. 1.2.2

Please provide any additional information below.

```

Original issue reported on code.google.com by `grrus...@googlemail.com` on 11 Mar 2014 at 2:05

**Comment by AlbertMietus** [comment]
There is a simple fix/workaround for this!

In file ``rst2pdf/basenodehandler.py``, (line 245, in elemdispatch), the TypeError is already ignored. Just add **KeyError** to!

filesnippet, with fix marked by 'GAM'
```
def elemdispatch(self, client, node, style=None):
        self = self.findsubclass(node, 'elemdispatch')

        # set anchors for internal references
        try:
            for i in node['ids']:
                client.pending_targets.append(i)
        except TypeError: #Happens with docutils.node.Text
            pass
        except KeyError as e: #GAM
            print("Ignored: %s on %s--GAM" % (e, node)) #GAM
            pass # GAM

        ... 

```
As you will see, it happens mainly to todo nodes (at least in my case:-) Surely you can remove the print

_Hopefully, someone will patch this soon (I don't have time to fork, patch, pull-request and hope it will be accepted. Just change it ..._
