### ISSUE TITLE
inline :math: fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#517]
```
What steps will reproduce the problem?
1. echo "This is :math:\`\\pi\`" > test.rst
2. rst2pdf test.rst -o test.pdf

What is the expected output? I expect a pdf with the symbol pi

What do you see instead? a python "ValueError"  (see the stack below)


Please answer the following questions, they are *very* important:

* Version of rst2pdf?
0.93.dev

* Version of reportlab?
from python, reportlab.__version__ is ' $Id$ '
and the egg says reportlab-3.1.8-py2.7-macosx-10.6-intel.egg


* Are you using wordaxe, and if true, what version?
don't think so

* Are you using rst2pdf with Sphinx, and if true, what version?
No


Please provide any additional information below.
When using inline math role, I get a python error, thus no pdf output. Because 
I don't understand it, I have no idea what test to do.
I paste the error stack below. I you have some idea of test to do, please tell 
me.

stack:
rst2pdf test.rst -o test.pdf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/rst2pdf", line 9, in <module>
    load_entry_point('rst2pdf==0.93.dev', 'console_scripts', 'rst2pdf')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/rst2pdf-0.93.dev-py2.7.egg/rst2pdf/genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/reportlab-3.1.8-py2.7-macosx-10.6-intel.egg/reportlab/platypus/paragraph.py", line 987, in __init__
    self._setup(text, style, bulletText or getattr(style,'bulletText',None), frags, cleanBlockQuotedText)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/reportlab-3.1.8-py2.7-macosx-10.6-intel.egg/reportlab/platypus/paragraph.py", line 1012, in _setup
    % (_parser.errors[0],text[:min(30,len(text))]))
ValueError: xml parser error (valign: invalid value -1.000000/) in paragraph 
beginning
'This is <img src="/var/folders'
```

Original issue reported on code.google.com by `julien.d...@gmail.com` on 30 Jul 2014 at 5:55

**Comment by tanderl** [comment]
I think I tracked this down to the HTMLParser module mis-handling the `<img/>` tag that gets created as part of the processing between docutils and the reportlab generation.  For details on the HTMLParser module issue, see http://bugs.python.org/issue26084.

I don't recommend it as a real fix, but to prove that it is the same problem, you can apply the same monkey patch that is listed in that bug, and then, rst2pdf works for me.

Alternatively, HTMLParser seems to parse quoted attributes correctly, so if whatever is generating the <img/> tags could be changed to produce quoted attributes, that would be a still-valid workaround for the HTMLParser problem.  I managed to dig down to `HandleParagraph.gather_elements` in genelements.py line 188 where it calls `client.gen_pdftext(node)`.  The conversion from a docutils structure to HTML happens somewhere inside of that.  If anyone can provide additional pointers for how to continue digging from there, they'd be appreciated.

**Comment by tanderl** [comment]
Correction to my above statement about the HTMLParser issue:  I was not careful enough in my reading of https://www.w3.org/TR/html5/syntax.html#attributes-0. It turns out this specific case is called out such that the current HTMLParser behavior is correct.

Thus I think it comes down to whatever is generating the <img> tag in the below trace needs to be updated to either quote the attribute values or put a space after the final attribute value and before the '/' character.  I think it comes down to the translation from a doctree latex node to the html of the paragraph.

Traceback (most recent call last):
  File "C:\Miniconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Miniconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\work\github\rst2pdf\rst2pdf\createpdf.py", line 1670, in <module>
    main(sys.argv[1:])
  File "C:\work\github\rst2pdf\rst2pdf\createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "C:\work\github\rst2pdf\rst2pdf\createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "C:\work\github\rst2pdf\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\work\github\rst2pdf\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\work\github\rst2pdf\rst2pdf\basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "C:\work\github\rst2pdf\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "C:\work\github\rst2pdf\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\work\github\rst2pdf\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\work\github\rst2pdf\rst2pdf\genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paragraph.py", line 1042, in __init__
    self._setup(text, style, bulletText or getattr(style,'bulletText',None), frags, cleanBlockQuotedText)
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paragraph.py", line 1064, in _setup
    style, frags, bulletTextFrags = _parser.parse(text,style)
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paraparser.py", line 1168, in parse
    annotateException('\nparagraph text %s caused exception' % ascii(text))
  File "C:\Miniconda\lib\site-packages\reportlab\lib\utils.py", line 1381, in annotateException
    rl_reraise(t,v,b)
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paraparser.py", line 1166, in parse
    self.feed(text)
  File "C:\Miniconda\lib\HTMLParser.py", line 117, in feed
    self.goahead(0)
  File "C:\Miniconda\lib\HTMLParser.py", line 163, in goahead
    k = self.parse_endtag(i)
  File "C:\Miniconda\lib\HTMLParser.py", line 401, in parse_endtag
    self.handle_endtag(elem)
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paraparser.py", line 1202, in handle_endtag
    end()
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paraparser.py", line 851, in end_para
    self._pop('para')
  File "C:\Miniconda\lib\site-packages\reportlab\platypus\paraparser.py", line 1007, in _pop
    raise ValueError('Parse error: saw </%s> instead of expected </%s>' % (tag,frag.__tag__))
ValueError: Parse error: saw </para> instead of expected </img>
paragraph text u'<para>The area of a circle is <img src="c:\\users\\tanderl\\appdata\\local\\temp\\tmpkccsvi.png" width=58.000000 height=13.000000 valign=-3.000
000/>.</para>' caused exception

**Comment by niejen** [comment]
I think the problem is a missing space in line 1653 of
[math2html.py](https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docutils/utils/math/math2html.py) :
    selfclosing = '<' + self.tag + '/>'
(should be + ' />' )

Is there some way for me to test this on ubuntu wily? (I've tried deleting the .pyc and editing the .py on my system, but it stubbornly refuses to let the changes affect rst2pdf...)
Anyways, if this fixes it, please send a heads-up to the docutils maintainers.

**Comment by niejen** [comment]
Found the error, this time with a tested fix:
Add a space in rst2pdf/math_directive.py line 103.

NOW I get a pdf with math symbols. Doesn't look fantastic, but it Works(tm).

**Comment by tanderl** [comment]
Thanks for the digging.  I'll try it out on my end.

**Comment by f0rdprefect** [comment]
can confirm the fix for me

**Comment by Grief** [comment]
@niejen thanks, that prevents the tool from crash. The result formula looks a little bit misaligned though. However, the project looks abandoned.
