### ISSUE TITLE
cannot install rst2pdf under CentOS release 5.11 with python 2.4.2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [rst2pdf/rst2pdf#523]
```
What steps will reproduce the problem?
1. Download and extract rst2pdf-0.93.tar.gz
2. Run sudo python setup.py install
3. Wait

What is the expected output?

A successful installation

What do you see instead?
The following (after some successful lines, see attachment):


Downloading 
https://pypi.python.org/packages/source/s/simplejson/simplejson-3.6.5.tar.gz
Processing simplejson-3.6.5.tar.gz
Running simplejson-3.6.5/setup.py -q bdist_egg --dist-dir 
/tmp/easy_install-d6BAKA/simplejson-3.6.5/egg-dist-tmp-uI6lnX
Traceback (most recent call last):
  File "setup.py", line 120, in ?
    test_suite='rst2pdf.tests.test_rst2pdf.test_suite',
  File "/usr/lib64/python2.4/distutils/core.py", line 149, in setup
    dist.run_commands()
  File "/usr/lib64/python2.4/distutils/dist.py", line 946, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.4/distutils/dist.py", line 966, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.4/site-packages/setuptools/command/install.py", line 76, in run
    self.do_egg_install()
  File "/usr/lib/python2.4/site-packages/setuptools/command/install.py", line 100, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 211, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 427, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 473, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 518, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 481, in resolve
    dist = best[req.key] = env.best_match(req, self, installer)
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 717, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.4/site-packages/pkg_resources.py", line 729, in obtain
    return installer(requirement)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 446, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 471, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 655, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 930, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.4/site-packages/setuptools/command/easy_install.py", line 919, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 26, in run_setup
    DirectorySandbox(setup_dir).run(
  File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 63, in run
    return func()
  File "/usr/lib/python2.4/site-packages/setuptools/sandbox.py", line 29, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 17
    with open('README.rst', 'r') as f:
            ^


Please answer the following questions, they are *very* important:

* Version of rst2pdf?

0.93

* Version of reportlab?
Not aware that I use it

* Are you using wordaxe, and if true, what version?
No
* Are you using rst2pdf with Sphinx, and if true, what version?
No
Please provide any additional information below.

Running on CentOS release 5.11 (Final) with Python 2.4.3

```

Original issue reported on code.google.com by `simon.br...@gmail.com` on 30 Jan 2015 at 2:10

Attachments:
- [build.log](https://storage.googleapis.com/google-code-attachments/rst2pdf/issue-523/comment-0/build.log)

**Comment by ralsina** [comment]
This is probably fixed or, alternatively, we should not care much about python 2.4
