### ISSUE TITLE
Referencing labeled table or figure fails PDF creation

### ISSUE THREAD

**Issue by Wargazm** [rst2pdf/rst2pdf#529]
If you label a table and then try to reference that table from within the body of a paragraph, PDF creation fails.

To reproduce, create new sphinx document with sphinx-quickstart and add support for rst2pdf in the makefiles and conf.py.  Then create a file with a single named table and a reference to the table, like so:

```
=====
TABLE
=====

Reference to table: :ref:`mytable`.

.. _mytable:

.. table:: My Table Title

   ====== ===== ===== ======= =======
   1      2     3     4       5
   ====== ===== ===== ======= =======
   1      2     3     4       5
   1      2     3     4       5
   1      2     3     4       5
   ====== ===== ===== ======= =======
```

run `make pdf` on the command line and witness the fail.    This is my stack trace:

```
C:\Users\aaguado\Desktop\temp\tablefail>make pdf
Running Sphinx v1.3.1
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 2 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] table
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing MyProject... index table
resolving references...
done
writing MyProject... [ERROR] pdfbuilder.py:130 list index out of range
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "C:\Python27\lib\site-packages\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "C:\Python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "C:\Python27\lib\site-packages\rst2pdf\genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "C:\Python27\lib\site-packages\rst2pdf\basenodehandler.py", line 279, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "C:\Python27\lib\site-packages\rst2pdf\genpdftext.py", line 232, in get_pre_post
    r = client.styleToTags(node['classes'][0])
IndexError: list index out of range
FAILED
build succeeded.
```

(confusingly, the output still says the build succeeded, which is probably another bug).  

I am on Windows, though I don't know if that's relevant.

I have created a dummy project (so you don't have to do all the project setup steps) if you wish to use that.  It's here:

https://www.dropbox.com/s/f3e81e0olpdz5g8/tablefail.zip?dl=0

Thanks!

**Comment by HenkVanAsselt** [comment]
FYI: I do see exactly the same symptoms with Sphinx 1.3.1, but I do not make use of tables as described here, I do make use of references.

**Comment by HenkVanAsselt** [comment]
I removed the only :ref: reference I used and after that the build of the pdf file succeeded.

The line

See also :ref:`vt220_characterset`

pointed to 

.. _vt220_characterset:

in the same .rst file.

**Comment by TheUserThatMustNotBeNamed** [comment]
This is affecting me as well.  Is there any workaround to get :ref: to work?

Thanks @HenkVanAsselt for taking the time to post.  It enabled me to get pdf's created, albeit sans :ref:'s.

**Comment by faridskyman** [comment]
i faced same issue, for the sake of getting a pdf, i duplicated the 'source' and replaced all :ref: and did get the pdf to be generated.

**Comment by trevor-vaughan** [comment]
Verifying that this is still an issue.

**Comment by emmanuelmathot** [comment]
I also have this issue. Any news on resolution?
