### ISSUE TITLE
Internal Hyperlink with rst2pdf can't work well

### ISSUE THREAD

**Issue by tanimani** [rst2pdf/rst2pdf#556]
I want to output internal hyperlink in PDF.

* os: mac os x (el capitan)
* python: 2.7.3 / 2.7.10 (this error occured both version)
* sphinx: 1.3.1

index.rst
```python
Header0
###############################

.. _internalref:

Header1
################################

* hogehoge
* hugahuga
* punipuni

Sub header1
===============================

:ref:`internalref`

Sub header2
===============================

hogehoge hugahuga punipuni

```
Then, run "make pdf" and Error of "Index Error list index out of range" happened.

```
sphinx-build -b pdf -d _build/doctrees   . _build/pdf
Running Sphinx v1.3.1
making output directory...
loading translations [ja]... done
WARNING: the config value 'version' has type `NoneType', defaults to `str.'
WARNING: the config value 'release' has type `NoneType', defaults to `str.'
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [100%] index                                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/user/Desktop/temp/contents/append.rst:: WARNING: document isn't included in any toctree
/Users/user/Desktop/temp/contents/append2.rst:: WARNING: document isn't included in any toctree
/Users/user/Desktop/temp/contents/append3.rst:: WARNING: document isn't included in any toctree
done
processing MyProject... index 
resolving references...
done
writing MyProject... [ERROR] pdfbuilder.py:130 list index out of range
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 279, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "/usr/local/var/pyenv/versions/2.7.3/lib/python2.7/site-packages/rst2pdf/genpdftext.py", line 232, in get_pre_post
    r = client.styleToTags(node['classes'][0])
IndexError: list index out of range
FAILED
build succeeded, 5 warnings.
```

I am not sure what is wrong in this situation.
FYI, this code work well at PortblePython2.7.3 in Windows7.

**Comment by dkriegner** [comment]
I could reproduce this bug with sphinx-1.3.5
It is however gone after upgrading to sphinx-1.4.1

Here the input data:
[doc.tar.gz](https://github.com/rst2pdf/rst2pdf/files/227881/doc.tar.gz)

Find below the two outputs of sphinx-build:

1.3.5
------

```
$ sphinx-build -b pdf doc/source/ build
Running Sphinx v1.3.5
loading pickled environment... failed: 'module' object has no attribute 'Symbol'
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                          
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing test... index 
resolving references...
done
writing test... [ERROR] pdfbuilder.py:130 list index out of range
[ERROR] pdfbuilder.py:130 list index out of range
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "/usr/lib64/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/lib64/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/genelements.py", line 442, in gather_elements
    elements = client.gather_elements(node)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/usr/lib64/python2.7/site-packages/rst2pdf/basenodehandler.py", line 279, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "/usr/lib64/python2.7/site-packages/rst2pdf/genpdftext.py", line 232, in get_pre_post
    r = client.styleToTags(node['classes'][0])
IndexError: list index out of range
FAILED
build succeeded.
```

1.4.1
------

```
sphinx-build -b pdf doc/source/ build/sphinx/
Running Sphinx v1.4.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [pdf]: targets for 1 source files that are out of date
updating environment: 1 added, 0 changed, 0 removed
reading sources... [100%] index                                          
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
processing test... index 
resolving references...
done
writing test... [WARNING] styles.py:548 Using undefined style 'std', aliased to style 'normal'.
[WARNING] styles.py:548 Using undefined style 'std', aliased to style 'normal'.
done
build succeeded.
```

**Comment by return42** [comment]
`nodes.emphasis` and `nodes.inline` are not having any classes and rst2pdf expects them to have any classes, this causes this `IndexError` exception. It's the same with the attribut `id` on various nodes, where rst2pdf makes a getitem on non existing properties. Sorry for saying this, but rst2pdf seems to have a lot of access on non existing properties.
