### ISSUE TITLE
Number limitation of image files

### ISSUE THREAD

**Issue by tanimani** [rst2pdf/rst2pdf#557]
Is there number limitation of image files?
rst2pdf can't work in case of over 250 image files.

* mac os x (El capitan)
* python 2.7.10
* rst2pdf 0.93

### 251 image files
```
327-105119-02:temp3 user$ rst2pdf index.rst
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.10/bin/rst2pdf", line 11, in <module>
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 1495, in main
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 582, in createPdf
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 108, in renderTemplate
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/tenjin.py", line 1062, in render
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/tenjin.py", line 1007, in get_template
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/tenjin.py", line 966, in create_template
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/tenjin.py", line 985, in read_template_file
IOError: [Errno 24] Too many open files: '/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/templates/cover.tmpl'
```

### 252 image files 
```
327-105119-02:temp3 user$ rst2pdf index.rst
[ERROR] image.py:357 The image (/Users/user/Documents/sample/temp3/_image/select_sync_252.png, near line UNKNOWN in file index.rst) is broken or in an unknown format
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/2.7.10/bin/rst2pdf", line 11, in <module>
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 1495, in main
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 561, in createPdf
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/genpdftext.py", line 158, in gather_elements
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/image.py", line 99, in __init__
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/image.py", line 36, in defaultimage
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/reportlab/platypus/flowables.py", line 412, in __init__
  File "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/reportlab/lib/utils.py", line 663, in open_for_read
IOError: Cannot open resource "/usr/local/var/pyenv/versions/2.7.10/lib/python2.7/site-packages/rst2pdf/images/image-missing.jpg"
```

**Comment by ralsina** [comment]
That looks like a limit on open files. While it's probably because rst2pdf is leaking file descriptors, a quick google shows a few workarounds:

http://superuser.com/questions/302754/increase-the-maximum-number-of-open-file-descriptors-in-snow-leopard

While that's for Snow Leopard, I expect the same thing happens in later versions of OSX
