### ISSUE TITLE
generating pdf for pywinauto fails while html output is OK

### ISSUE THREAD

**Issue by vasily-v-ryabov** [rst2pdf/rst2pdf#564]
I'm trying to generate pdf documentation for the pywinauto project (Win8.1 x64). conf.py is updated according to the [Handbook (18)](http://rst2pdf.ralsina.me/handbook.html). Steps to reproduce:
1. Get [pywinauto sources](https://github.com/vasily-v-ryabov/pywinauto/tree/UIA)
2. Install Sphinx and rst2pdf by pip.
3. Run `sphinx-build -w warnings.txt -E -b pdf .\doc_src .\pdf_docs 1>sphinx_build_log.txt 2>stderr.txt` in the pywinauto repo root folder.

Output:

``` python
[ERROR] pdfbuilder.py:130 format not resolved, probably missing URL scheme or undefined destination target for 'module-pywinauto.actionlogger'
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "C:\Python27\lib\site-packages\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "C:\Python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "C:\Python27\lib\site-packages\rst2pdf\createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "C:\Python27\lib\site-packages\reportlab\platypus\doctemplate.py", line 1024, in multiBuild
    self.canv.save()
  File "C:\Python27\lib\site-packages\reportlab\pdfgen\canvas.py", line 1215, in save
    self._doc.SaveToFile(self._filename, self)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 219, in SaveToFile
    data = self.GetPDFData(canvas)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 244, in GetPDFData
    return self.format()
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 424, in format
    IOf = IO.format(self)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 869, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 80, in format
    f = element.format(document)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 1606, in format
    return D.format(document)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 676, in format
    L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 80, in format
    f = element.format(document)
  File "C:\Python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 1782, in format
    if f is None: raise ValueError("format not resolved, probably missing URL scheme or undefined destination target for '%s'" % self.name)
ValueError: format not resolved, probably missing URL scheme or undefined destination target for 'module-pywinauto.actionlogger'
```

HTML output is OK with the command:

```
sphinx-build -w warnings.txt -E -b html .\doc_src .\gen_docs 1>sphinx_build_log.txt 2>stderr.txt
```

87 warnings is not a showstopper for the correct [HTML output](http://pywinauto.github.io/docs/).

TeX is not installed on the system. I believe it's not required, right?

**Comment by ralsina** [comment]
In this case, this probably indicates there is an internal link pointing to
somewhere that doesn't exist. In PDF you can't have broken internal links.

**Comment by An0Mee** [comment]
Was this problem resolved?

**Comment by vasily-v-ryabov** [comment]
@An0Mee yes, this was resolved a long time ago. PDF docs are available here: https://pywinauto.readthedocs.io/_/downloads/en/latest/pdf/ (from ReadTheDocs page you can scroll down at the left bar and click on "v:latest" link where you will see the menu with "Download PDF" link among others.

**Comment by sachin-suresh-rapyuta** [comment]
Finally, where is the solution to this issue?

**Comment by vasily-v-ryabov** [comment]
We used these requirements:
```
Babel==1.3
mock==2.0.0
rst2pdf
six==1.10.0
Sphinx==1.4.1
```
and generated pdf for Windows package on Linux machine (Read-the-Docs builds the docs on Linux even if it is Windows only package). This is what I remember in few words. More details can be found here: https://github.com/pywinauto/pywinauto/pull/182.
