### ISSUE TITLE
Renamed links are not working

### ISSUE THREAD

**Issue by fdev31** [rst2pdf/rst2pdf#569]
Something used to work on other rst parsers:

```
`Foobar <test_>`_

.. _test:  http://google.com

```

Leads to an exception:

```
Traceback (most recent call last):
  File "/usr/bin/rst2pdf", line 9, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 1495, in main
    compressed=options.compressed)
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 561, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 205, in gather_elements
    return client.gather_elements(node, style=style)
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 390, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 250, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 225, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/lib/python2.7/site-packages/rst2pdf/genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 266, in get_text
    return client.gather_pdftext(node)
  File "/usr/lib/python2.7/site-packages/rst2pdf/createpdf.py", line 380, in gather_pdftext
    for n in node.children])
  File "/usr/lib/python2.7/site-packages/rst2pdf/basenodehandler.py", line 279, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "/usr/lib/python2.7/site-packages/rst2pdf/genpdftext.py", line 225, in get_pre_post
    if node['ids'][0] not in client.targets:
IndexError: list index out of range
```

I manually patch the latest file regularly to skip that case, so I suppose it's an old bug

**Comment by ralsina** [comment]
Yep, real bug.
