### ISSUE TITLE
rst2pdf executable raises "TypeError: Cannot mix str and non-str arguments" 

### ISSUE THREAD

**Issue by kevmitch** [rst2pdf/rst2pdf#596]
Since c0ff1fbd62a9e76f5aebfb2b6a72ccfe3a35fd33, it seems that no matter what arguments or input is given the following exception is raised:

```
(rst2pdf.env) $ rst2pdf
Traceback (most recent call last):
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 1354, in main
    parser = parse_commandline()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 1184, in parse_commandline
    def_baseurl = urlunparse(['file',os.getcwd()+os.sep,'','','',''])
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/urllib/parse.py", line 387, in urlunparse
    _coerce_args(*components))
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/future-0.15.2-py2.7.egg/future/backports/urllib/parse.py", line 115, in _coerce_args
    raise TypeError("Cannot mix str and non-str arguments")
TypeError: Cannot mix str and non-str arguments
```

**Comment by netmonk** [comment]
got exactly the same issue with a clone from yesterday.

**Comment by a1s** [comment]
+1.
It works if I remove line 44:

`from __future__ import unicode_literals`

**Comment by netrounds-joakim** [comment]
@oz123 Can you please look at this bug as well? This Python 3 stuff is breaking a lot of things, at least when using Python 2.

**Comment by alexwlchan** [comment]
Found it. Thanks to @a1s’s comment, I put together the following minimal repro:

```python
from __future__ import unicode_literals

from future import standard_library
standard_library.install_aliases()

import os
from urllib.parse import urlunparse

args = ['file', os.getcwd() + os.sep, '', '', '', '']
print(repr(args))
print(urlunparse(args))
```

Running this, you get the following line, then the TypeError:

```
[u'file', '/Users/alexwlchan/repos/rst2pdf/', u'', u'', u'', u'']
```

Apparently `os.getcwd()` returns a bytestring, not a Unicode string. Explicitly setting the other arguments to `urlunparse` to be byte strings fixes the issue; patch incoming.

**Comment by ralsina** [comment]
This is fixed already
