### ISSUE TITLE
reportlab.platypus.doctemplate.LayoutError building mpv pdf manual with --repeat-table-rows

### ISSUE THREAD

**Issue by kevmitch** [rst2pdf/rst2pdf#597]
In both bd2668154c3989159d295663deba33c9775ab6cc (which is the most recent commit that doesn't raise unicode exceptions for me), as well as the latest 0.93 release, the [mpv manual fails to build](https://github.com/mpv-player/mpv/issues/3563) with the --repeat-table-rows argument. Without this argument it seem to work OK. Using the [.rst files](https://kevmitch.ca/mpvrst.zip) from mpv 89674854ceaae9c0a9d8f24b9a24fb2f24df6bb1:

```
(rst2pdf.env) $ rst2pdf --repeat-table-rows mpv.rst
Traceback (most recent call last):
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 1499, in main
    compressed=options.compressed)
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 655, in createPdf
    pdfdoc.multiBuild(elements)
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/reportlab-3.3.0-py2.7-linux-x86_64.egg/reportlab/platypus/doctemplate.py", line 1043, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/reportlab-3.3.0-py2.7-linux-x86_64.egg/reportlab/platypus/doctemplate.py", line 956, in build
    self.handle_flowable(flowables)
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/rst2pdf-0.93.dev_r0-py2.7.egg/rst2pdf/createpdf.py", line 804, in handle_flowable
    self.handle_frameEnd()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/reportlab-3.3.0-py2.7-linux-x86_64.egg/reportlab/platypus/doctemplate.py", line 670, in handle_frameEnd
    self.handle_pageEnd()
  File "/home/kevmitch/src/rst2pdf/rst2pdf.env/lib/python2.7/site-packages/reportlab-3.3.0-py2.7-linux-x86_64.egg/reportlab/platypus/doctemplate.py", line 616, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
```

**Comment by lornajane** [comment]
Looks like the related issue was marked as fixed so I am closing this one as well
