### ISSUE TITLE
AttributeError: PDFWriter instance has no attribute 'custom_cover'

### ISSUE THREAD

**Issue by chrchr** [rst2pdf/rst2pdf#601]
```
Traceback (most recent call last):
  File "/Users/rchurch/sphinx_tst/venv/lib/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "/Users/rchurch/sphinx_tst/venv/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/Users/rchurch/sphinx_tst/venv/lib/python2.7/site-packages/rst2pdf/pdfbuilder.py", line 577, in translate
    log.error("Can't find cover template %s, using default"%self.custom_cover)
AttributeError: PDFWriter instance has no attribute 'custom_cover'
```

This happens with `pdf_cover_template` set in conf.py.

```
$ rst2pdf --version
0.93.dev-r0
$ python --version
Python 2.7.12
$ uname -a
Darwin computer 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64
```

**Comment by pshchelo** [comment]
To note the bahaviour change - it seems now (with newer Jinja2) the value of `pdf_cover_template` setting should be **short name** (w/o path) to the template instead of a full name.

**Comment by akrabat** [comment]
0.97 is now release with this fix in it.
