### ISSUE TITLE
TypeError: module.__init__() argument 1 must be str, not bytes

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [rst2pdf/rst2pdf#602]
I installed rst2pdf the following way:

    conda create --name rst2pdf python=3.5
    source activate rst2pdf
    mkdir rst2pdf
    pushd rst2pdf
    git clone https://github.com/rst2pdf/rst2pdf .
    python setup.py install
    (gives error about needing `jpeg`)
    conda install jpeg
    (installs jpeg without issue)
    python setup.py install
    (this time runs fine)

Then I switch to my document's directory and run:

    pushd mydocdir
    rst2pdf mydoc.rst mydoc-rst2pdf.pdf

Which gives me the following error:

	Traceback (most recent call last):
	  File "/home/hans/development/anaconda3/envs/rst2pdf/bin/rst2pdf", line 11, in <module>
	    load_entry_point('rst2pdf===0.93.dev-r0', 'console_scripts', 'rst2pdf')()
	  File "/home/hans/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
	    return get_distribution(dist).load_entry_point(group, name)
	  File "/home/hans/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
	    return ep.load()
	  File "/home/hans/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2291, in load
	    return self.resolve()
	  File "/home/hans/.local/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2297, in resolve
	    module = __import__(self.module_name, fromlist=['__name__'], level=0)
	  File "/home/hans/development/anaconda3/envs/rst2pdf/lib/python3.5/site-packages/rst2pdf-0.93.dev_r0-py3.5.egg/rst2pdf/createpdf.py", line 109, in <module>
	    from rst2pdf import tenjin
	  File "/home/hans/development/anaconda3/envs/rst2pdf/lib/python3.5/site-packages/rst2pdf-0.93.dev_r0-py3.5.egg/rst2pdf/tenjin.py", line 249, in <module>
	    helpers = _create_helpers_module()
	  File "/home/hans/development/anaconda3/envs/rst2pdf/lib/python3.5/site-packages/rst2pdf-0.93.dev_r0-py3.5.egg/rst2pdf/tenjin.py", line 233, in _create_helpers_module
	    mod = _create_module('tenjin.helpers')
	  File "/home/hans/development/anaconda3/envs/rst2pdf/lib/python3.5/site-packages/rst2pdf-0.93.dev_r0-py3.5.egg/rst2pdf/tenjin.py", line 92, in _create_module
	    mod = ModuleType(module_name.split('.')[-1].encode())
	TypeError: module.__init__() argument 1 must be str, not bytes

What did I do wrong?

**Comment by pya** [comment]
Unfortunately, Python 3 is not supported yet. Looks like it is in the works. I saw pull request dealing with porting to Python 3: #588
