### ISSUE TITLE
hyphenation broken

### ISSUE THREAD

**Issue by rkoe** [rst2pdf/rst2pdf#611]
Hyphenation does not work at all in rst2pdf, even if wordaxe and pyhyphen are installed.

rst2pdf --verbose does not show any hyphenation-error-messages, but also does not do any hyphenation.

Versions used:
- rst2pdf: 0.93.dev-r0 (from Debian Jessie)
- wordaxe 1.0.1

**Comment by ralsina** [comment]
This is because wordaxe doesn't support newer reportlab versions. It is throwing this error which is masked by rst2pdf:

```
Traceback (most recent call last):
  File "/Users/ralsina/.virtualenvs/rst2pdf/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')()
  File "/Users/ralsina/.virtualenvs/rst2pdf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/ralsina/.virtualenvs/rst2pdf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/Users/ralsina/.virtualenvs/rst2pdf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/Users/ralsina/.virtualenvs/rst2pdf/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/ralsina/code/rst2pdf/rst2pdf/createpdf.py", line 45, in <module>
    from opt_imports import psyco
  File "/Users/ralsina/code/rst2pdf/rst2pdf/opt_imports.py", line 24, in <module>
    from wordaxe.rl.paragraph import Paragraph
  File "/Users/ralsina/.virtualenvs/rst2pdf/lib/python2.7/site-packages/wordaxe/rl/paragraph.py", line 11, in <module>
    from wordaxe.rl.NewParagraph import *
  File "/Users/ralsina/.virtualenvs/rst2pdf/lib/python2.7/site-packages/wordaxe/rl/NewParagraph.py", line 1185, in <module>
    from reportlab.lib.utils import fp_str
ImportError: cannot import name fp_str
```

**Comment by ralsina** [comment]
I will fork wordaxe (which is abandonware) and do a fix there.

**Comment by ralsina** [comment]
Also, pyhyphen seems to be unable to download dictionaries nowadays, which will break things.

**Comment by ralsina** [comment]
Using https://github.com/ralsina/wordaxe instead of the default wordaxe it **seems** to work, at least for spanish:

<img width="588" alt="screen shot 2018-09-17 at 13 48 32" src="https://user-images.githubusercontent.com/1579/45637282-6e112e00-ba80-11e8-865e-e6a89c4d033b.png">
