### ISSUE TITLE
Get error when I start rst2pdf

### ISSUE THREAD

**Issue by Shadowell** [rst2pdf/rst2pdf#630]
E:\PyProject\GAWDataStandard>rst2pdf -h
Traceback (most recent call last):
  File "E:\Data\PBT\Python\Python36\Scripts\rst2pdf-script.py", line 11, in <module>
    load_entry_point('rst2pdf==0.93.dev0', 'console_scripts', 'rst2pdf')()
  File "E:\Data\PBT\Python\Python36\site-packages\pkg_resources\__init__.py", line 572, in loa
d_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "E:\Data\PBT\Python\Python36\site-packages\pkg_resources\__init__.py", line 2769, in lo
ad_entry_point
    return ep.load()
  File "E:\Data\PBT\Python\Python36\site-packages\pkg_resources\__init__.py", line 2422, in lo
ad
    return self.resolve()
  File "E:\Data\PBT\Python\Python36\site-packages\pkg_resources\__init__.py", line 2428, in re
solve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "E:\Data\PBT\Python\Python36\site-packages\rst2pdf\createpdf.py", line 695
    except ValueError, v:
                     ^
SyntaxError: invalid syntax

**Comment by akrabat** [comment]
As @oz123 says, rst2pdf is a Python 2 application.

**Comment by epogrebnyak** [comment]
> rst2pdf is a Python 2 application.

Maybe mention this in the docs?
