### ISSUE TITLE
this raises error in runpy.py for python3.6

### ISSUE THREAD

**Issue by agrawalharshit** [rst2pdf/rst2pdf#641]
C:\>rst2pdf index.rst output.pdf
Traceback (most recent call last):
  File "c:\users\harsh\appdata\local\programs\python\python36-32\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\harsh\appdata\local\programs\python\python36-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\harsh\AppData\Local\Programs\Python\Python36-32\Scripts\rst2pdf.exe\__main__.py", line 5, in <module>
  File "c:\users\harsh\appdata\local\programs\python\python36-32\lib\site-packages\rst2pdf\createpdf.py", line 695
    except ValueError, v:
                     ^
SyntaxError: invalid syntax

C:\>

**Comment by akrabat** [comment]
I suspect that you’re using Python 3. At the moment, rst2pdf is a Python 2 project, though we intend to move to Python 3.

**Comment by Liso77** [comment]
Could you at least disallow pip install in python3 environment by properly fix requirement.txt?
