### ISSUE TITLE
sphinx + rst2pdf error: unexpected keyword argument 'ts'

### ISSUE THREAD

**Issue by Tok3nizer** [rst2pdf/rst2pdf#678]
### Problem
I was using sphinx and rst2pdf without any problems but the issue occured today upon a fresh installation on another PC. I'm no longer able to generate the documentation in pdf format. The only difference between my configuration and the new one is the sphinx version: I have v1.7.4 while the new pc has v.1.7.6 (installed by default with pip install command).

#### Procedure to reproduce the problem
```
sphinx-build -b pdf source build/pdf
```

#### Error logs / results
```
writing MyDocsTryOut... [ERROR] pdfbuilder.py:130 __init__() got an unexpected keyword argument 'ts'
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "c:\python27\lib\site-packages\docutils\writers\__init__.py", line 80, in write
    self.translate()
  File "c:\python27\lib\site-packages\rst2pdf\pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "c:\python27\lib\site-packages\rst2pdf\createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "c:\python27\lib\site-packages\reportlab\platypus\doctemplate.py", line 1135, in multiBuild
    self.canv.save()
  File "c:\python27\lib\site-packages\reportlab\pdfgen\canvas.py", line 1240, in save
    self._doc.SaveToFile(self._filename, self)
  File "c:\python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 215, in SaveToFile
    data = self.GetPDFData(canvas)
  File "c:\python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 241, in GetPDFData
    return self.format()
  File "c:\python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 418, in format
    IOf = IO.format(self)
  File "c:\python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 866, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
  File "c:\python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 80, in format
    f = element.format(document)
  File "c:\python27\lib\site-packages\reportlab\pdfbase\pdfdoc.py", line 1546, in format
    D['ModDate'] = D["CreationDate"] = PDFDate(ts=document._timeStamp,dateFormatter=self._dateFormatter)
TypeError: __init__() got an unexpected keyword argument 'ts'
```

### Environment info
- OS: Windows 10
- Python version: 2.7.15
- Sphinx version:  1.7.6

**Comment by benjdj6** [comment]
Experiencing the same issue, have attempted on multiple Sphinx and Python versions.

OS: macOS 10.13.5
Python versions attempted: 2.7.8, 2.7.13
Sphinx versions attempted: 1.2.3, 1.6.5, 1.7.4, 1.7.6

**Comment by benjdj6** [comment]
Hey @Tok3nizer, I have found a workaround solution. Remove the `ts=` in line 1546 in `pdfdoc.py`. The path to the file is printed in the last line of the trace. rst2pdf should be patched to handle the keyword arguments used by reportlab. Unfortunately I'm not knowledgeable enough myself to do so.

**Comment by lornajane** [comment]
Thank you so much for reporting this bug and helping one another. This is super useful and will help us a lot in finding and fixing this bug!  Can you share what version of reportlab you're using (either/both of you) please?

**Comment by benjdj6** [comment]
The offending change was introduced [in this change](https://bitbucket.org/rptlab/reportlab/diff/src/reportlab/pdfbase/pdfdoc.py?diff2=d39c63b164bc&at=default) for ReportLab version 3.4.2. While full support for newer versions of ReportLab is added you can just add `<3.4.2` to the `setup.py`. It didn't break anything locally when I did this.

**Comment by ralsina** [comment]
rst2pdf was patching reportlab's PDFDate class because it didn't support invariant dates.

I proposed a simple fix adding support for a dummy ts option in rst2pdf's patched PDFDate

Alternatively, we could make rst2pdf use reportlab's ts option when it gets the invariant flag, but that would do the same thing in the end while requiring harder testing.

**Comment by 1-riverfish** [comment]
I have solved this issue, refer this link
https://github.com/rst2pdf/rst2pdf/commit/14668d34523e21faf21ba6bca20e623aa3c33de6.
