### ISSUE TITLE
make pdf for sphinx-build fails with LayoutError in reportlab/platypus/doctemplate.py

### ISSUE THREAD

**Issue by rezroo** [rst2pdf/rst2pdf#679]
I can build each individual .rst file using "rst2pdf <file>.rst" and get .pdf file.
However when running "make pdf" I get:
```
[ERROR] pdfbuilder.py:130 More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/pdfbuilder.py", line 127, in write
    docwriter.write(doctree, destination)
  File "/usr/local/lib/python2.7/dist-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/pdfbuilder.py", line 621, in translate
    compressed=self.compressed)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 653, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 1125, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 1038, in build
    self.handle_flowable(flowables)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 801, in handle_flowable
    self.handle_frameEnd()
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 689, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/local/lib/python2.7/dist-packages/reportlab/platypus/doctemplate.py", line 632, in handle_pageEnd
    raise LayoutError(ident)
LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
FAILED
```

Where should I look, or what should I try next?
Versions:
```
$ sphinx-build --version
sphinx-build 1.7.6

# ls /usr/local/lib/python2.7/dist-packages/{rst2pdf,reportlab}*.dist-info
/usr/local/lib/python2.7/dist-packages/reportlab-3.5.4.dist-info:
INSTALLER  METADATA  RECORD  top_level.txt  WHEEL

/usr/local/lib/python2.7/dist-packages/rst2pdf-0.93.dev_r0.dist-info:
dependency_links.txt  entry_points.txt  METADATA       RECORD         WHEEL
DESCRIPTION.rst       INSTALLER         metadata.json  top_level.txt
```

**Comment by lornajane** [comment]
Can you show us the contents of your `Makefile`? Without seeing that, it's hard to know what's happening here. The error `Likely that a flowable is too large for any frame` is (in my experience) almost always the cause but it can be hard to know _which_ flowable

**Comment by rezroo** [comment]
I don't think there are any changes to this standard Makefile. Here you go - had to change the extension to .txt so it could be an attachment:

[Makefile.txt](https://github.com/rst2pdf/rst2pdf/files/2281140/Makefile.txt)

**Comment by akrabat** [comment]
Usually, "more than 10 pages generated without content" occurs when an image is too large and isn't being scaled or there's a really large block of text or a table that can't fit onto one page or be wrapped.

In this case, as you can build each rst file, I'm confused! Maybe try building just 2 rst files with `make` and then add each rst file until you find which one it's upset with?

**Comment by mseashor** [comment]
**Summary**: I was also getting the `more than 10 pages generated without content` with sphinx rst2pdf build (using sphinx-click to generate content).  In my particular case, the issue was the index become too wide and I fixed this issue with `pdf_use_index = False`.  

Just posting this info as it might be helpful to others even though, as said above, *any* flowable that's too wide can cause issues (not just the index) so this is likely not a solution for all with this error.

**Details**
Prior to getting `more than 10 pages generated without content` I would get a ton of `BoundByWidth too wide to fit in frame`  (see: https://github.com/rst2pdf/rst2pdf/issues/260) of I was able to workaround the index issues for a while using `pdf_break_level = 0` (https://github.com/rst2pdf/rst2pdf/issues/260#issuecomment-223575914).   The index pages still looked bad, as they were too wide for the page.

However as the document became larger (more commands created with click), I would consistently get `LayoutError: More than 10 pages generated without content - halting layout` and an empty PDF.  Given the index is not overly helpful in our case (index was in two columns that overlapped each other and went off the page), disabling the index with `pdf_use_index = False` fixed both errors and makes the document look better.

**Comment by sachin-suresh-rapyuta** [comment]
I have used `pdf_use_index = False` and still get the same error. I also tried to remove the `width:` attribute in the img.

Here is my error trace:

```
[ERROR] pdfbuilder.py:161 Failed to build doc
Traceback (most recent call last):
  File "/home/sachin/.local/lib/python3.8/site-packages/rst2pdf/pdfbuilder.py", line 158, in write
    docwriter.write(doctree, destination)
  File "/home/sachin/.local/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/sachin/.local/lib/python3.8/site-packages/rst2pdf/pdfbuilder.py", line 697, in translate
    createpdf.RstToPdf(
  File "/home/sachin/.local/lib/python3.8/site-packages/rst2pdf/createpdf.py", line 689, in createPdf
    pdfdoc.multiBuild(elements)
  File "/usr/lib/python3/dist-packages/reportlab/platypus/doctemplate.py", line 1143, in multiBuild
    self.build(tempStory, **buildKwds)
  File "/usr/lib/python3/dist-packages/reportlab/platypus/doctemplate.py", line 1056, in build
    self.handle_flowable(flowables)
  File "/home/sachin/.local/lib/python3.8/site-packages/rst2pdf/createpdf.py", line 862, in handle_flowable
    self.handle_frameEnd()
  File "/usr/lib/python3/dist-packages/reportlab/platypus/doctemplate.py", line 709, in handle_frameEnd
    self.handle_pageEnd()
  File "/usr/lib/python3/dist-packages/reportlab/platypus/doctemplate.py", line 651, in handle_pageEnd
    raise LayoutError(ident)
reportlab.platypus.doctemplate.LayoutError: More than 10 pages generated without content - halting layout.  Likely that a flowable is too large for any frame.
```
