### ISSUE TITLE
rst2pdf with Python3

### ISSUE THREAD

**Issue by GSebastian-Adil** [rst2pdf/rst2pdf#681]
# Problem

******@******:~/projects/Sphinx$ sphinx-build -b pdf source build/pdf
Running Sphinx v1.7.8

Exception occurred:
File "/home/******/.local/lib/python3.6/site-packages/sphinx/registry.py", line 315, in load_extension
mod = import(extname, None, None, ['setup'])
File "/home/******/.local/lib/python3.6/site-packages/rst2pdf/pdfbuilder.py", line 129
except Exception, e:
^
SyntaxError: invalid syntax
The full traceback has been saved in /tmp/sphinx-err-_9n6c5ti.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!
Procedure to reproduce the problem

# Error logs / results

 ----------sphinx-err-_9n6c5ti.log----------
- Sphinx version: 1.7.8
- Python version: 3.6.5 (CPython)
- Docutils version: 0.14 
- Jinja2 version: 2.10
- Last messages:

- Loaded extensions:
Traceback (most recent call last):
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/cmdline.py", line 303, in main
    args.warningiserror, args.tags, args.verbosity, args.jobs)
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/application.py", line 191, in __init__
    self.setup_extension(extension)
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/application.py", line 411, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/******/.local/lib/python3.6/site-packages/sphinx/registry.py", line 315, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/******/.local/lib/python3.6/site-packages/rst2pdf/pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax

**Comment by lornajane** [comment]
I'm sorry but this is expected behaviour since rst2pdf still depends on python2 at this point in time. We'd like that to change and help in this direction is always welcome!
