### ISSUE TITLE
Math is broken in Sphinx 1.8.0+

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#722]
`sphinx-issue252` no longer works with Sphinx 1.8.0+

http://www.sphinx-doc.org/en/master/usage/extensions/math.html notes:

> Changed in version 1.8: Math support for non-HTML builders is integrated to sphinx-core. So mathbase extension is no longer needed.

This will require updating `sphinxnodes.py` and `pdfbuilder.py` I think.

**Output of sphinx-issue252:**

```
$ ./autotest.py input/sphinx-issue252
Process "make" started on Thu Dec 20 22:22:15 2018

        make clean pdf


  rm -rf _build/*
  sphinx-build -b html -d _build/doctrees   . _build/html
  Running Sphinx v1.8.2
  making output directory...
  building [mo]: targets for 0 po files that are out of date
  building [html]: targets for 1 source files that are out of date
  updating environment: 1 added, 0 changed, 0 removed
  reading sources... [100%] index

  looking for now-outdated files... none found
  pickling environment... done
  checking consistency... done
  preparing documents... done
  writing output... [100%] index

  generating indices... genindex
  writing additional pages... search
* WARNING: html_static_path entry u'/Users/rob/Projects/python/rst2pdf/rst2pdf/tests/input/sphinx-issue252/_static' does not exist
  copying static files... done
  copying extra files... done
  dumping search index in English (code: en) ... done
  dumping object inventory... done
  build succeeded, 1 warning.

  The HTML pages are in _build/html.

  Build finished. The HTML pages are in _build/html.
  sphinx-build -b pdf -d _build/doctrees   . _build/pdf
  Running Sphinx v1.8.2
  making output directory...
  loading pickled environment... done
  building [mo]: targets for 0 po files that are out of date
  building [pdf]: targets for 1 source files that are out of date
  updating environment: 0 added, 0 changed, 0 removed
  looking for now-outdated files... none found
  processing MyProject...
  index
  resolving references...
  done
  writing MyProject...
* [WARNING] basenodehandler.py:164 Unkn. node (self.textdispatch): docutils.nodes.math [near line UNKNOWN in file UNKNOWN]
* [WARNING] basenodehandler.py:164 Unkn. node (self.elemdispatch): docutils.nodes.math_block [near line 13 in file /Users/rob/Projects/python/rst2pdf/rst2pdf/tests/input/sphinx-issue252/index.rst]
* [ERROR] pdfbuilder.py:133 format not resolved, probably missing URL scheme or undefined destination target for 'equation-euler'
* Traceback (most recent call last):
*   File "/Users/rob/Projects/python/rst2pdf/rst2pdf/pdfbuilder.py", line 130, in write
*     docwriter.write(doctree, destination)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/docutils/writers/__init__.py", line 80, in write
*     self.translate()
*   File "/Users/rob/Projects/python/rst2pdf/rst2pdf/pdfbuilder.py", line 633, in translate
*     compressed=self.compressed)
*   File "/Users/rob/Projects/python/rst2pdf/rst2pdf/createpdf.py", line 655, in createPdf
*     pdfdoc.multiBuild(elements)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/platypus/doctemplate.py", line 1133, in multiBuild
*     self.canv.save()
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfgen/canvas.py", line 1240, in save
*     self._doc.SaveToFile(self._filename, self)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 215, in SaveToFile
*     data = self.GetPDFData(canvas)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 241, in GetPDFData
*     return self.format()
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 418, in format
*     IOf = IO.format(self)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 866, in format
*     fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 80, in format
*     f = element.format(document)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 1602, in format
*     return D.format(document)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 674, in format
*     L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 80, in format
*     f = element.format(document)
*   File "/Users/rob/.pyenv/versions/2.7.15/envs/rst2pdf/lib/python2.7/site-packages/reportlab/pdfbase/pdfdoc.py", line 1767, in format
*     if f is None: raise ValueError("format not resolved, probably missing URL scheme or undefined destination target for '%s'" % self.name)
* ValueError: format not resolved, probably missing URL scheme or undefined destination target for 'equation-euler'
  FAILED
  build succeeded.

  Build finished. The PDF files are in _build/pdf.

Program make exit code: PASS (0)   elapsed time: 05.4 seconds

Validity of file sphinx-issue252.pdf checksum 'd41d8cd98f00b204e9800998ecf8427e' is unknown.


Final checksum statistics:
unknown=1
```

**Comment by ralsina** [comment]
A more basic problem is that currently rst2pdf implements its own math directive, which is not needed anymore since there is one in docutils.

I am starting a PR that deletes all the custom directive/role and uses docutils, that should fix this.

**Comment by ralsina** [comment]
This simple rst file:

```
.. math::

  α_t(i) = P(O_1, O_2, … O_t, q_t = S_i λ)
```

Gives this:

```
[WARNING] basenodehandler.py:164 Unkn. node (self.elemdispatch): docutils.nodes.math_block [near line 3 in file x.rst]
```

I think the same is true about the code block support, rst2pdf implements its own and docutils has since added one. The "bad" news there is that rst2pdf's supports some extra functionality so it's not trivial to remove it.
