### ISSUE TITLE
The oddeven directive and the use-numbered-links option are incompatible

### ISSUE THREAD

**Issue by waltsteverson** [rst2pdf/rst2pdf#727]
**Description of problem**
When try to run rst2pdf on the test file for the oddeven directive and enable the --use-numbered-links command-line option I get an exception.
```bash
$ rst2pdf test_oddeven.txt --use-numbered-links -o output.pdf
Traceback (most recent call last):
  File "/usr/local/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf==0.93.dev0', 'console_scripts', 'rst2pdf')()
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf-0.93.dev0-py2.7.egg/rst2pdf/createpdf.py", line 1502, in main
    compressed=options.compressed)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf-0.93.dev0-py2.7.egg/rst2pdf/createpdf.py", line 553, in createPdf
    self.doctree.walk(snf)
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 138, in walk
    if child.walk(visitor):
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 130, in walk
    visitor.dispatch_visit(self)
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 1882, in dispatch_visit
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 1907, in unknown_visit
    % (self.__class__, node.__class__.__name__))
NotImplementedError: rst2pdf.sectnumlinks.SectNumFolder visiting unknown node type: OddEvenNode
```

 **Versions**
```bash
$ python -V && pip freeze
Python 2.7.15rc1
aafigure==0.6
alabaster==0.7.12
asn1crypto==0.24.0
Babel==2.6.0
backports.functools-lru-cache==1.5
certifi==2018.11.29
chardet==3.0.4
cryptography==2.1.4
cycler==0.10.0
docutils==0.14
enum34==1.1.6
html5lib==1.0.1
idna==2.8
imagesize==1.1.0
ipaddress==1.0.17
Jinja2==2.10
keyring==10.6.0
keyrings.alt==3.0
kiwisolver==1.0.1
MarkupSafe==1.1.0
matplotlib==2.2.3
numpy==1.15.4
packaging==18.0
pdfrw==0.4
Pillow==5.3.0
pycrypto==2.6.1
Pygments==2.3.0
pygobject==3.26.1
pyparsing==2.3.0
PyPDF2==1.26.0
python-dateutil==2.7.5
pytz==2018.7
pyxdg==0.25
reportlab==3.5.12
requests==2.21.0
rst2pdf==0.93.dev0
SecretStorage==2.3.1
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.7.9
sphinxcontrib-websupport==1.1.0
subprocess32==3.5.3
svg2rlg==0.3
typing==3.6.6
urllib3==1.24.1
webencodings==0.5.1
xhtml2pdf==0.2.3
```

Which operating system are you using?
Ubuntu 18.04 (bionic)

**Additional information**
I have a requirement to alternate the header based on whether the page is an odd or even page.  Without these options playing together nicely I will most likely be forced into manually numbering all sections which is time-consuming and suboptimal.

**Comment by waltsteverson** [comment]
Apparently the same thing happens with CounterNode as well and probably all of the custom nodes registered by rst2pdf.

**Comment by ralsina** [comment]
If you could check the code in #728 it's just a few lines and should fix it.
