### ISSUE TITLE
Cannot build manual on Python 2

### ISSUE THREAD

**Issue by akrabat** [rst2pdf/rst2pdf#757]
After merging #744, the manual no longer builds on my Python 2.7.16:

```
$ cd doc
$ rst2pdf manual.rst --custom-cover=assets/cover.tmpl -o output/pdf/manual.pdf -s assets/manual.style -b1
Traceback (most recent call last):
  File "/Users/rob/.pyenv/versions/rst2pdf/bin/rst2pdf", line 11, in <module>
    load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')()
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/createpdf.py", line 1506, in main
    strip_elements_with_classes=options.strip_elements_with_classes,
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/createpdf.py", line 184, in __init__
    self.loadStyles(stylesheets)
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/createpdf.py", line 288, in loadStyles
    def_dpi=self.def_dpi)
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/styles.py", line 358, in __init__
    fontList = findfonts.autoEmbed(style[key])
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/findfonts.py", line 316, in autoEmbed
    variants = findTTFont(fname)
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/findfonts.py", line 221, in findTTFont
    return get_variants(family)
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/findfonts.py", line 204, in get_variants
    get_fname(family + ":style=Roman"),
  File "/Users/rob/Projects/python/rst2pdf/rst2pdf/findfonts.py", line 198, in get_fname
    if line.startswith("file: "):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 36: ordinal not in range(128)
```

```

**Comment by akrabat** [comment]
Any thoughts @ralsina?

**Comment by ralsina** [comment]
I can't reproduce.

**Comment by akrabat** [comment]
That's interesting. I wonder if it's specific to my environment.

**Comment by akrabat** [comment]
The problem is here:

```python
    def get_fname(query):
        data = os.popen("fc-match -v \"%s\""%query, "r").read()
        for line in data.splitlines():
            line = line.strip()
            if line.startswith("file: "):
                return line.split('"')[1]
        return None
```

It's failing on `if line.startswith("file: "):` where `line` is:

```
style: "Regular"(s) "Normal"(s) "obyčejné"(s) "Standard"(s) "Κανονικά"(s) "Normaali"(s) "Normál"(s) "Normale"(s) "Standaard"(s) "Normalny"(s) "Обычный"(s) "Normálne"(s) "Navadno"(s) "Arrunta"(s)
```

I assume the problem is related to the non-ascii characters in Python 2 as this works in Python 3.
