### ISSUE TITLE
Windows path to `cover.tmpl` raises `jinja2.TemplateNotFound`

### ISSUE THREAD

**Issue by natebragg** [rst2pdf/rst2pdf#766]
This is the encountered exception:

    rst2pdf tutorial.rst
    Traceback (most recent call last):
      File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
        "__main__", fname, loader, pkg_name)
      File "c:\python27\lib\runpy.py", line 72, in _run_code
        exec code in run_globals
      File "C:\Python27\Scripts\rst2pdf.exe\__main__.py", line 9, in <module>
      File "c:\python27\lib\site-packages\rst2pdf\createpdf.py", line 1511, in main
        compressed=options.compressed)
      File "c:\python27\lib\site-packages\rst2pdf\createpdf.py", line 591, in createPdf
        subtitle=self.doc_subtitle
      File "c:\python27\lib\site-packages\rst2pdf\createpdf.py", line 112, in renderTemplate
        template =jinja_env.get_template(tname)
      File "c:\python27\lib\site-packages\jinja2\environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "c:\python27\lib\site-packages\jinja2\environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "c:\python27\lib\site-packages\jinja2\loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "c:\python27\lib\site-packages\jinja2\loaders.py", line 168, in get_source
        pieces = split_template_path(template)
      File "c:\python27\lib\site-packages\jinja2\loaders.py", line 31, in split_template_path
        raise TemplateNotFound(template)
    jinja2.exceptions.TemplateNotFound: c:\python27\lib\site-packages\rst2pdf\templates\cover.tmpl

Digging a little revealed that [jinja2 expects only posix-style paths for templates](https://github.com/pallets/jinja/issues/711).

The simplest solution would be to punt on finding `cover.tmpl`, and let jinja2 find it.

Python 2.7.16
rst2pdf==0.94
reportlab==3.5.17

My OS is Windows.

**Comment by natebragg** [comment]
Fixed by pull request #767
