### ISSUE TITLE
Crash on hyperlinks with embedded internal link alias

### ISSUE THREAD

**Issue by rartino** [rst2pdf/rst2pdf#820]
Reading the rst specification, in particular the section about embedded uris and aliases:

- https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html#embedded-uris-and-aliases

I expect the following useful constructs to be supported:
```
Title
=====

This is a `hyperlink with an embedded link alias <Title_>`_.
```

and

```
Oh yes, the _`Norwegian Blue`.  What's, um, what's wrong with it?

This is a `link <Norwegian Blue_>`_.
```

However, they crash rst2pdf with the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/rst2pdf", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 1511, in main
    compressed=options.compressed)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 570, in createPdf
    elements = self.gen_elements(self.doctree)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 251, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 226, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 206, in gather_elements
    return client.gather_elements(node, style=style)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 400, in gather_elements
    r.extend(self.gen_elements(n, style=style))
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 251, in elemdispatch
    elements = self.getelements(client, node, style)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 226, in getelements
    elements = self.gather_elements(client, node, style)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/genelements.py", line 188, in gather_elements
    return [Paragraph(client.gen_pdftext(node), style)]
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 281, in textdispatch
    text = self.get_text(client, node, replaceEnt)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 267, in get_text
    return client.gather_pdftext(node)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/createpdf.py", line 390, in gather_pdftext
    for n in node.children])
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/basenodehandler.py", line 280, in textdispatch
    pre, post = self.get_pre_post(client, node, replaceEnt)
  File "/usr/local/lib/python2.7/dist-packages/rst2pdf/genpdftext.py", line 237, in get_pre_post
    pre = u'<a name="%s"/>' % node['refuri']
  File "/usr/local/lib/python2.7/dist-packages/docutils/nodes.py", line 585, in __getitem__
    return self.attributes[key]
KeyError: 'refuri'
```
They work as expected with, e.g., rst2html.

Expected behavior: no crash, but instead the pdf contains an anchor hyperlink that links the hyperlink to the internal target that the alias references.

**Versions**
Python 2.7.15+
rst2pdf===0.94.1
reportlab==3.5.32
OS: Ubuntu 18.04.3 LTS

**Comment by lornajane** [comment]
Seems similar to #964 but maybe not exactly identical

**Comment by rartino** [comment]
@lornajane I'd say #964 is a direct duplicate of this bug. 

The example given in #964 is exactly the same as my first example. (Although, #964 adds the helpful info that the example does not crash rst2pdf if one instead makes the reference anonymous by using a double underscore suffix rather than a single one.)

**Comment by nfraprado** [comment]
Yes, these are certainly the same bug. Though as @rartino said, the information that anonymous links don't cause the issue mentioned on #964 will probably help in fixing it. Also, it serves to show that the issue is still there in python 3, since this issue was reported using python 2. In any case, @lornajane , feel free to close #964.
