### ISSUE TITLE
Incorrect processing of headings.

### ISSUE THREAD

**Issue by normanlorrain** [rst2pdf/rst2pdf#833]
Note:  I'd love to see this work on Windows, so I'm happy to contribute. I just need some guidance to get started.

When creating the manual.pdf file, I get the following errors: 

**Description of problem**
```
...
  File "D:\github\rst2pdf\venv\lib\site-packages\docutils\utils\__init__.py", line 195, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: D:\github\rst2pdf/doc/manual.rst:1062: (SEVERE/4) Title level inconsistent:

File inclusion
**************
```

and
```
...
  File "D:\github\rst2pdf\venv\lib\site-packages\docutils\utils\__init__.py", line 237, in severe
  File "D:\github\rst2pdf\venv\lib\site-packages\docutils\utils\__init__.py", line 195, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: D:\github\rst2pdf/doc/manual.rst:1128: (SEVERE/4) Title level inconsistent:

Raw PDF
*******

```

I thought it might be an issue with the document, but Pandoc processes it OK, and the PDF on the web site looks fine.

🖥 **Versions**
- Python 3.8.1
- `pip freeze | grep rst2pdf`
 -e git+https://github.com/normanlorrain/rst2pdf.git@4d617f348d967f54679294c7ef5dc21f45e34923#egg=rst2pdf
- Windows 10

Also fails on the command-line
```
(venv) D:\github\rst2pdf\doc>rst2pdf DEVELOPERS.rst

(venv) D:\github\rst2pdf\doc>rst2pdf manual.rst
manual.rst:1060: (SEVERE/4) Title level inconsistent:

File inclusion
**************
Traceback (most recent call last):
  File "D:\github\rst2pdf\venv\Scripts\rst2pdf-script.py", line 11, in <module>
    load_entry_point('rst2pdf', 'console_scripts', 'rst2pdf')()
  File "d:\github\rst2pdf\rst2pdf\createpdf.py", line 1463, in main
    RstToPdf(
  File "d:\github\rst2pdf\rst2pdf\createpdf.py", line 530, in createPdf
    self.doctree = docutils.core.publish_doctree(text,
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\core.py", line 481, in publish_doctree
    output = pub.publish(enable_exit_status=enable_exit_status)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\core.py", line 216, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\readers\__init__.py", line 71, in read
    self.parse()
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\readers\__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\__init__.py", line 191, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 3007, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 326, in section
    if self.check_subsection(source, style, lineno):
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 367, in check_subsection
    self.parent += self.title_inconsistent(source, lineno)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\parsers\rst\states.py", line 371, in title_inconsistent
    error = self.reporter.severe(
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\utils\__init__.py", line 237, in severe
    return self.system_message(self.SEVERE_LEVEL, *args, **kwargs)
  File "d:\github\rst2pdf\venv\lib\site-packages\docutils\utils\__init__.py", line 195, in system_message
    raise SystemMessage(msg, level)
docutils.utils.SystemMessage: manual.rst:1060: (SEVERE/4) Title level inconsistent:

File inclusion
**************
```

**Comment by sandrotosi** [comment]
in order to build 0.95 for Debian, we needed to apply the following patch: with that in, the HTML doc renders like https://rst2pdf.org/static/manual.html
[fix-doc.patch.txt](https://github.com/rst2pdf/rst2pdf/files/4016802/fix-doc.patch.txt)

**Comment by akrabat** [comment]
@sandrotosi Thanks. I'll have a fix out tomorrow.

**Comment by akrabat** [comment]
[rst2pdf 0.96](https://pypi.org/project/rst2pdf/0.96/) is now released.

This is the only change, so we have a source release where the manual builds correctly.
