### ISSUE TITLE
versionlabels dict is empty

### ISSUE THREAD

**Issue by 2bndy5** [rst2pdf/rst2pdf#981]
I'm trying to build docs (with rst2pdf) using sphinx, and I'm getting an error related to the `versionadded` and `versionchanged` directives.
### rST code in question
```rst
   .. versionadded:: 0.0.5
```
```rst
   .. versionchanged:: 0.0.5
      removed ``only_new`` parameter in favor of using `available()`
```
### Entire output
```python
[ERROR] pdfbuilder.py:159 Failed to build doc
Traceback (most recent call last):
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py", line 156, in write
    docwriter.write(doctree, destination)
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\docutils\writers\__init__.py", line 78, in write
    self.translate()
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py", line 587, in translate
    self.document.walkabout(visitor)
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\docutils\nodes.py", line 214, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 8 more times]
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\docutils\nodes.py", line 206, in walkabout
    visitor.dispatch_visit(self)
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\docutils\nodes.py", line 1995, in dispatch_visit
    return method(node)
  File "c:\users\%USER_NAME%\appdata\local\programs\python\python38-32\lib\site-packages\rst2pdf\pdfbuilder.py", line 738, in visit_versionmodified
    text = versionlabels[node['type']] % node['version']
KeyError: 'versionadded'
FAILED
```
### Attempted debugging
When I added some debugging print statements to `visit_versionmodified()` I found that the `versionlabels` dict is empty. 😕  I can confirm that the directive and their args are gathered correctly.
```python
    def visit_versionmodified(self, node):
        print(node['type'], node['version'])  # verify directive and arg is correct
        print(versionlabels)  # verify that no keys named `versionadded` or `versionchanged` exist
        text = versionlabels[node['type']] % node['version']
        if len(node):
            text += ': '
        else:
            text += '.'
        replacement = nodes.paragraph()
        replacement += nodes.Text(text)
        replacement.extend(node.children)
        node.parent.replace(node, replacement)
```
the print statements output:
```text
versionadded 0.0.5
{}
```
and for the `versionchanged` directive:
```text
versionchanged 0.0.5
{}
```
### EDIT
This problem might be instigated by a Sphinx change because I found this declaration in Sphinx's `__init__.py`:
```python
# Moved to sphinx.directives.other (will be overriden later)
versionlabels = {}  # type: Dict[str, str]
```
after some more digging, I found the dict with expected values in `Sphinx.domain.changeset.py`
```python
versionlabels = {
    'versionadded':   _('New in version %s'),
    'versionchanged': _('Changed in version %s'),
    'deprecated':     _('Deprecated since version %s'),
}
```
So, I assume this issue is likely affecting the `deprecated` directive also.
## Versions
- Python 3.8.2 (3.8.5 on WSL ubuntu)
- rst2pdf 0.98
- reportlab 3.5.59
- Sphinx 3.0.3 (3.4.3 on WSL ubuntu)

this output is consistent using Windows 10 and WSL ubuntu (with version listed above)

**Comment by 2bndy5** [comment]
I think I solved this. Changing ([this line](https://github.com/rst2pdf/rst2pdf/blob/257d3b0bc48cc57546d5e2543bf4c2855e99bd07/rst2pdf/pdfbuilder.py#L38))
```python
from sphinx.locals import versionlabels
```
to
```python
from sphinx.domains.changeset import versionlabels
```
doesn't produce the error anymore.

**Comment by 2bndy5** [comment]
ok, I fixed the duplicate text entry by removing the prepending 
```python
replacement += node.Text(text)
```
from `visit_versionmodified()`. The output produced is now
>_New in version 0.0.5_.

and for `versionchanged` directive
>_Changed in version 0.0.5_: removed `only_new` parameter in favor of using `available()`.

which is what I expect from comparing this to the html output.
